rapport_final.pdf: rapport_final.tex
	rubber --pdf rapport_final.tex

presentation.pdf:presentation.tex
	rubber --pdf presentation.tex

clean: 
	rm *.aux *.out *.toc *.log *.bbl *.blg *.nav *.snm *.vrb
